/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:0220fe76-4473-456d-a9a1-dc69b03a20ba",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_5oOUBIyW0",
    "aws_user_pools_web_client_id": "78a5fc2n4uvq7mr50grk1rteb9",
    "oauth": {}
};


export default awsmobile;
